pipeline {
    agent any

    stages {
        stage('Pull Dockerhub') {
            steps {
                sh 'docker pull adriananogueira/tema_01_final:tagname'
            }
        }
        stage('Docker run') {
            steps {
                sh 'docker run  -d -p 8085:8085 adriananogueira/tema_01_final'
            }
        }
    }
}