pipeline {
    agent any

    environment {
        ARTIFACTORY_SERVER = 'jfrog-cli' // Nome da credencial global
    }

    stages {
        stage('Build') {
            steps {
                script {
                    def server = Artifactory.server ARTIFACTORY_SERVER
                    server.deployer.createMavenBuildInfo = true
                    server.resolver.createMavenBuildInfo = true
                    server.deployer.mavenBuildInfo = server.resolver.mavenBuildInfo
                }
            }
        }
    }
}
