pipeline {
    agent any

    stages {
        stage('Upload to Artifactory') {
            steps {
                script {
                    def server = Artifactory.server 'calculadora'
                    def uploadSpec = """{
                        "files": [
                            {
                                "pattern": "build/libs/*.jar",
                                "target": "caluladora/"
                            }
                        ]
                    }"""
                    server.upload(uploadSpec)
                }
            }
        }
    }
}
