pipeline {
    agent any

    stages {
        stage('Test JFrog Artifactory Credentials') {
            steps {
                script {
                    def server = Artifactory.server 'calculadora'

                    // Exemplo de listagem de artefatos de um repositório
                    def repo = 'seu-repo-de-teste'
                    def artifactList = server.listArtifacts(repo: repo)

                    echo "Lista de Artefatos no Repositório ${repo}:"
                    echo "${artifactList}"
                }
            }
        }
    }
}
