pipeline {
    agent any

    environment {
        ARTIFACTORY_SERVER_ID = credentials('artifactory_server_id')
    }

    stages {
        stage('Build') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'docker_hub_credentials', usernameVariable: 'DOCKERHUB_USERNAME', passwordVariable: 'DOCKERHUB_PASSWORD')]) {
                    sh '''
                       packer build -var 'dockerhub_username=adriananogueira' -var 'dockerhub_password=123Mudar@' ./Job-02/packer-template.pkr.hcl

                    '''
                }
            }
        }
    }
}
